name: Automated Script Runner

on:
  schedule:
    - cron: "30 10 * * 1-5"  # runs daily at 4 PM IST
  workflow_dispatch:  # allows manual trigger

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Google Chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install
          google-chrome --version

      - name: Install dependencies
        run: |
          pip install gspread gspread-formatting kiteconnect pandas requests retrying tqdm \
            google-auth google-auth-oauthlib google-auth-httplib2 webdriver-manager selenium pyotp

      - name: Recreate secret files (keep Mac path)
        env:
          API_KEY_VS: ${{ secrets.API_KEY_VS }}
          ACCESS_TOKEN_VS: ${{ secrets.ACCESS_TOKEN_VS }}
          CREDS_VS_JSON: ${{ secrets.CREDS_VS_JSON }}
        run: |
          set -e
          # Mac-like directory
          sudo mkdir -p /Users/sugamkuchhal/Documents/kite-gtt-demo-vs

          # --- Write to Mac path (your hardcoded locations)
          [ -n "$API_KEY_VS" ] && printf '%s' "$API_KEY_VS" | sudo tee /Users/sugamkuchhal/Documents/kite-gtt-demo-vs/api_key_vs.txt > /dev/null
          [ -n "$ACCESS_TOKEN_VS" ] && printf '%s' "$ACCESS_TOKEN_VS" | sudo tee /Users/sugamkuchhal/Documents/kite-gtt-demo-vs/access_token_vs.txt > /dev/null
          [ -n "$CREDS_VS_JSON" ] && printf '%s' "$CREDS_VS_JSON" | sudo tee /Users/sugamkuchhal/Documents/kite-gtt-demo-vs/creds_vs.json > /dev/null
          sudo chmod 600 /Users/sugamkuchhal/Documents/kite-gtt-demo-vs/creds_vs.json || true

          # --- ALSO write to repo root (what your code opens: "api_key_vs.txt")
          [ -n "$API_KEY_VS" ] && printf '%s' "$API_KEY_VS" > api_key_vs.txt
          [ -n "$ACCESS_TOKEN_VS" ] && printf '%s' "$ACCESS_TOKEN_VS" > access_token_vs.txt

          # quick sanity
          ls -l api_key_vs.txt access_token_vs.txt

      - name: Run scripts
        run: |
          python3 fetch_holdings_vs.py
          python3 fetch_all_gtts_vs.py
