name: Automated Script Runner

on:
  schedule:
    - cron: "30 10 * * 1-5"  # runs daily at 4 PM IST
  workflow_dispatch:      # allows manual trigger from GitHub

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Google Chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install
          google-chrome --version

      - name: Install dependencies
        run: |
          pip install gspread gspread-formatting kiteconnect pandas requests retrying tqdm \
            google-auth google-auth-oauthlib google-auth-httplib2 webdriver-manager selenium pyotp

      - name: Create credential files
        env:
          API_KEY: ${{ secrets.API_KEY_VS }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_VS }}
          CREDS_JSON: ${{ secrets.CREDS_VS_JSON }}
       run: |
          mkdir -p /Users/sugamkuchhal/Documents/kite-gtt-demo-vs
          [ -n "$API_KEY_VS" ] && echo "$API_KEY_VS" > /Users/sugamkuchhal/Documents/kite-gtt-demo-vs/api_key_vs.txt || true
          [ -n "$ACCESS_TOKEN_VS" ] && echo "$ACCESS_TOKEN_VS" > /Users/sugamkuchhal/Documents/kite-gtt-demo-vs/access_token_vs.txt || true
          [ -n "$CREDS_VS_JSON" ] && echo "$CREDS_VS_JSON" > /Users/sugamkuchhal/Documents/kite-gtt-demo-vs/creds_vs.json || true

      - name: Run scripts
        run: |
          python3 fetch_holdings_vs.py
          python3 nse_combined_fetcher.py --mode stock \
            --ticker-file nse_stock_list.txt \
            --worksheet "NSE_Stock_Data" \
            --csv nse_stock_data.csv \
            --max-workers 10 \
            --batch-size 200
          bash combined_run.sh
